from __future__ import annotations


DEFAULT_HATS: list[dict] = [
    {
        "id": "executive",
        "name": "Executive",
        "role": "Owns the goal, priorities, stopping conditions, and routing decisions.",
        "system_prompt": (
            "You are the Executive hat inside a single-role cognitive cluster. "
            "Keep the objective clear, choose what matters now, resolve tradeoffs, "
            "and decide whether to continue, revise, ask the user, or finish."
        ),
        "model": "auto",
        "temperature": 0.2,
        "tools": [],
        "color": "#4cc9f0",
        "icon": "compass",
        "can_write_blackboard": True,
        "can_prompt_hats": True,
    },
    {
        "id": "planner",
        "name": "Planner",
        "role": "Turns the goal into steps, dependencies, unknowns, and next actions.",
        "system_prompt": (
            "You are the Planner hat. Break the task into concrete steps, name dependencies, "
            "call out unknowns, and propose the next smallest useful action."
        ),
        "model": "auto",
        "temperature": 0.25,
        "tools": [],
        "color": "#7ddc82",
        "icon": "list",
        "can_write_blackboard": True,
        "can_prompt_hats": False,
    },
    {
        "id": "context_keeper",
        "name": "Context Keeper",
        "role": "Maintains the live situation model: facts, assumptions, memory, and constraints.",
        "system_prompt": (
            "You are the Context Keeper. Extract the current facts, assumptions, constraints, "
            "open questions, and memory-relevant details. Prefer concise structured notes."
        ),
        "model": "auto",
        "temperature": 0.15,
        "tools": ["memory_search"],
        "color": "#c8a4ff",
        "icon": "archive",
        "can_write_blackboard": True,
        "can_prompt_hats": False,
    },
    {
        "id": "worker",
        "name": "Worker",
        "role": "Executes the concrete task packet without trying to be the whole mind.",
        "system_prompt": (
            "You are the Worker hat. Execute the assigned task directly. Be concrete, "
            "produce useful output, and return evidence rather than broad commentary."
        ),
        "model": "auto",
        "temperature": 0.3,
        "tools": ["web_search", "filesystem_read", "filesystem_write"],
        "color": "#ffd166",
        "icon": "wrench",
        "can_write_blackboard": True,
        "can_prompt_hats": False,
    },
    {
        "id": "critic",
        "name": "Critic",
        "role": "Looks for weak reasoning, contradictions, missing cases, and premature closure.",
        "system_prompt": (
            "You are the Critic hat. Challenge the current answer. Find flaws, missing cases, "
            "unclear assumptions, and signs of overconfidence. Do not solve unless needed."
        ),
        "model": "auto",
        "temperature": 0.2,
        "tools": [],
        "color": "#ff6b6b",
        "icon": "alert",
        "can_write_blackboard": True,
        "can_prompt_hats": True,
    },
    {
        "id": "verifier",
        "name": "Verifier",
        "role": "Demands checks, evidence, tests, citations, screenshots, or reproducible proof.",
        "system_prompt": (
            "You are the Verifier hat. Check whether the result satisfies the goal. "
            "Name required evidence, pass/fail status, and unresolved verification gaps. "
            "Do not rubber-stamp plausible answers: enumerate concrete branches or examples when possible, "
            "test them against every constraint, and fail outputs with contradictions."
        ),
        "model": "auto",
        "temperature": 0.1,
        "tools": ["filesystem_read", "shell"],
        "color": "#2bd9a3",
        "icon": "check",
        "can_write_blackboard": True,
        "can_prompt_hats": False,
    },
    {
        "id": "memory_curator",
        "name": "Memory Curator",
        "role": "Decides what should be stored, updated, merged, forgotten, or marked stale.",
        "system_prompt": (
            "You are the Memory Curator. Convert the run into durable memory candidates. "
            "Preserve provenance, avoid noise, and mark stale or uncertain facts."
        ),
        "model": "auto",
        "temperature": 0.15,
        "tools": ["memory_write"],
        "color": "#f78c6b",
        "icon": "database",
        "can_write_blackboard": True,
        "can_prompt_hats": False,
    },
]


DEFAULT_TOPOLOGY: dict = {
    "schema_version": 2,
    "id": "general_super_agent_cluster",
    "name": "General Super Agent Cluster",
    "nodes": [
        {
            "id": "executive",
            "type": "hat",
            "hat_id": "executive",
            "name": "Executive",
            "role": "Owns goal framing, routing, tradeoffs, stopping criteria, and final approval.",
            "authority": ["route", "revise_plan", "final_approval"],
            "visibility": "full_blackboard",
            "output_contract": "Decision, success criteria, routing choice, or final approved answer.",
            "x": 360,
            "y": 54,
        },
        {
            "id": "context_keeper",
            "type": "hat",
            "hat_id": "context_keeper",
            "name": "Context Keeper",
            "role": "Maintains facts, assumptions, constraints, and the live situation model.",
            "authority": ["write_state"],
            "visibility": "full_blackboard",
            "output_contract": "Concise facts, assumptions, constraints, and open questions.",
            "x": 120,
            "y": 174,
        },
        {
            "id": "planner",
            "type": "hat",
            "hat_id": "planner",
            "name": "Planner",
            "role": "Turns the goal and context into task packets with dependencies and checks.",
            "authority": ["delegate", "write_state"],
            "visibility": "full_blackboard",
            "output_contract": "Task packet, dependency notes, and benchmark-oriented success checks.",
            "x": 360,
            "y": 174,
        },
        {
            "id": "worker",
            "type": "hat",
            "hat_id": "worker",
            "name": "Worker",
            "role": "Executes concrete task packets and revises work after review gates.",
            "authority": ["execute", "write_state"],
            "visibility": "task_packet_and_blackboard",
            "output_contract": "Direct answer or artifact with supporting evidence.",
            "x": 600,
            "y": 174,
        },
        {
            "id": "blackboard",
            "type": "store",
            "name": "Blackboard",
            "role": "Shared structured state for facts, plan, assumptions, evidence, objections, and decisions.",
            "authority": [],
            "visibility": "shared_state",
            "output_contract": "Readable state snapshot.",
            "store_key": "blackboard",
            "color": "#9fb7ff",
            "x": 120,
            "y": 318,
        },
        {
            "id": "task_ledger",
            "type": "store",
            "name": "Task Ledger",
            "role": "Task packets, dependencies, acceptance criteria, and revision requests.",
            "authority": [],
            "visibility": "shared_state",
            "output_contract": "Ordered task packets and status.",
            "store_key": "task_packets",
            "color": "#7ddc82",
            "x": 360,
            "y": 318,
        },
        {
            "id": "evidence_store",
            "type": "store",
            "name": "Evidence Store",
            "role": "Artifacts, tests, citations, screenshots, logs, and verification material.",
            "authority": [],
            "visibility": "shared_state",
            "output_contract": "Evidence items with provenance.",
            "store_key": "evidence",
            "color": "#2bd9a3",
            "x": 600,
            "y": 318,
        },
        {
            "id": "critic_gate",
            "type": "gate",
            "name": "Critic Gate",
            "role": "Blocks shallow completion by forcing adversarial review before verification.",
            "authority": ["block", "request_revision"],
            "visibility": "work_product",
            "output_contract": "Pass, revise, or escalate with specific defects.",
            "color": "#ff6b6b",
            "x": 250,
            "y": 452,
        },
        {
            "id": "critic",
            "type": "hat",
            "hat_id": "critic",
            "name": "Critic",
            "role": "Finds weak reasoning, missing cases, contradictions, and premature closure.",
            "authority": ["interrupt", "request_revision"],
            "visibility": "work_product_and_blackboard",
            "output_contract": "Specific defects and required revisions.",
            "x": 250,
            "y": 548,
        },
        {
            "id": "verifier_gate",
            "type": "gate",
            "name": "Verifier Gate",
            "role": "Requires evidence before the Executive can approve final output.",
            "authority": ["block", "request_evidence"],
            "visibility": "work_product_and_evidence",
            "output_contract": "Pass/fail status, evidence quality, and remaining proof gaps.",
            "color": "#2bd9a3",
            "x": 500,
            "y": 452,
        },
        {
            "id": "verifier",
            "type": "hat",
            "hat_id": "verifier",
            "name": "Verifier",
            "role": "Checks goal satisfaction and demands tests, citations, logs, or reproducible proof.",
            "authority": ["verify", "request_evidence"],
            "visibility": "work_product_and_evidence",
            "output_contract": "Verification verdict with exact evidence and unresolved gaps.",
            "x": 500,
            "y": 548,
        },
        {
            "id": "memory_curator",
            "type": "hat",
            "hat_id": "memory_curator",
            "name": "Memory Curator",
            "role": "Extracts durable lessons, provenance, and stale/uncertain memory notes.",
            "authority": ["write_memory"],
            "visibility": "trace_and_blackboard",
            "output_contract": "Memory candidates worth preserving after the run.",
            "x": 720,
            "y": 452,
        },
        {
            "id": "memory_store",
            "type": "store",
            "name": "Memory Store",
            "role": "Durable memory candidates and procedural improvements.",
            "authority": [],
            "visibility": "curated_state",
            "output_contract": "Memory records with provenance and confidence.",
            "store_key": "memory_candidates",
            "color": "#f78c6b",
            "x": 720,
            "y": 548,
        },
        {
            "id": "final_output",
            "type": "output",
            "name": "Final Output",
            "role": "User-facing answer after executive approval and verifier evidence.",
            "authority": [],
            "visibility": "approved_result",
            "output_contract": "Clean final answer without internal trace noise.",
            "color": "#42c6ff",
            "x": 60,
            "y": 548,
        },
    ],
    "edges": [
        {
            "id": "e_context_request",
            "source": "executive",
            "target": "context_keeper",
            "type": "context",
            "blocking": True,
            "payload": "Frame the goal and request situation-state extraction.",
        },
        {
            "id": "e_context_write",
            "source": "context_keeper",
            "target": "blackboard",
            "type": "state",
            "blocking": False,
            "payload": "Facts, assumptions, constraints, and open questions.",
        },
        {
            "id": "e_plan_request",
            "source": "executive",
            "target": "planner",
            "type": "delegation",
            "blocking": True,
            "payload": "Create a benchmark-oriented task plan.",
        },
        {
            "id": "e_plan_write",
            "source": "planner",
            "target": "task_ledger",
            "type": "state",
            "blocking": False,
            "payload": "Task packet, dependencies, and acceptance checks.",
        },
        {
            "id": "e_task_to_worker",
            "source": "planner",
            "target": "worker",
            "type": "delegation",
            "blocking": True,
            "payload": "Concrete task packet for execution.",
        },
        {
            "id": "e_task_context",
            "source": "task_ledger",
            "target": "worker",
            "type": "context",
            "blocking": False,
            "payload": "Current task packet and acceptance criteria.",
        },
        {
            "id": "e_worker_evidence",
            "source": "worker",
            "target": "evidence_store",
            "type": "state",
            "blocking": False,
            "payload": "Work product and supporting evidence.",
        },
        {
            "id": "e_worker_critic_gate",
            "source": "worker",
            "target": "critic_gate",
            "type": "review",
            "blocking": True,
            "payload": "Work must face adversarial critique before continuing.",
        },
        {
            "id": "e_critic_gate_to_critic",
            "source": "critic_gate",
            "target": "critic",
            "type": "review",
            "blocking": True,
            "payload": "Run defect search on the current work product.",
        },
        {
            "id": "e_critic_revision",
            "source": "critic",
            "target": "worker",
            "type": "escalation",
            "blocking": True,
            "payload": "Specific revisions required before verification.",
        },
        {
            "id": "e_worker_verifier_gate",
            "source": "worker",
            "target": "verifier_gate",
            "type": "review",
            "blocking": True,
            "payload": "Revised work must be checked against evidence.",
        },
        {
            "id": "e_verifier_gate_to_verifier",
            "source": "verifier_gate",
            "target": "verifier",
            "type": "review",
            "blocking": True,
            "payload": "Demand evidence and pass/fail the result.",
        },
        {
            "id": "e_verifier_to_executive",
            "source": "verifier",
            "target": "executive",
            "type": "approval",
            "blocking": True,
            "payload": "Verification verdict used for final approval.",
        },
        {
            "id": "e_executive_final",
            "source": "executive",
            "target": "final_output",
            "type": "approval",
            "blocking": True,
            "payload": "Approved user-facing answer.",
        },
        {
            "id": "e_blackboard_memory_context",
            "source": "blackboard",
            "target": "memory_curator",
            "type": "context",
            "blocking": False,
            "payload": "Facts and decisions relevant to durable memory.",
        },
        {
            "id": "e_evidence_memory_context",
            "source": "evidence_store",
            "target": "memory_curator",
            "type": "context",
            "blocking": False,
            "payload": "Evidence provenance for memory candidates.",
        },
        {
            "id": "e_memory_write",
            "source": "memory_curator",
            "target": "memory_store",
            "type": "state",
            "blocking": False,
            "payload": "Curated memory candidates.",
        },
    ],
}
